name: Emotes
main: io.github.com.revenantgaze.emoteplugin.Main
version: 1.5 BETA 1.0
author: RevenantGaze
website: http://dev.bukkit.org/bukkit-plugins/emotes/
commands:
  emotes:
    description: Gives access to the /emotes command!
    usage: /emotes
    default: op
    permission: emotes.command.emotes.use
  emotes list:
    description: Lists all available emotes!
    usage: /emotes list
    default: op
    permission: emotes.command.emotes.list
  emotes cooldown:
    description: Shows the help message for the emotes cooldown command!
    usage: /emotes cooldown change <seconds>
    default: op
    permission: emotes.command.emotes.cooldown
  emotes cooldown change:
    description: Changes the duration of the emotes cooldown!
    usage: /emotes cooldown change <seconds>
    default: op
    permission: emotes.command.emotes.cooldown.change
  emotes cooldown show:
    description: Show the cooldown value!
    usage: /emotes cooldown show
    default: op
    permission: emotes.command.emotes.show
  emotes cooldown default:
    description: Changes the duration of the emotes cooldown to default!
    usage: /emotes cooldown change <seconds>
    default: op
    permission: emotes.command.emotes.default
  kiss:
    description: Kiss another player!
    usage: /kiss <player>
    default: op
    permission: emotes.command.kiss
  hug:
    description: Hug another player!
    usage: /hug <player>
    default: op
    permission: emotes.command.hug
  wave:
    description: Wave at another player!
    usage: /wave <player>
    default: op
    permission: emotes.command.wave
  glomp:
    description: Glomp a player!
    usage: /glomp <player>
    default: op
    permission: emotes.command.glomp
  wink:
    description: Wink to a player!
    usage: /wink <player>
    default: op
    permission: emotes.command.wink
  ekick:
    description: Kick a player in their private parts!
    usage: /ekick <player>
    default: op
    permission: emotes.command.kick
    aliases: 
      - emote_kick
      - emoteskick
      - emotekick
  teabag:
    description: Teabag a player!
    usage: /teabag <player>
    default: op
    permission: emotes.command.teabag
  flail:
    description: Flail!
    usage: /flail
    default: op
    permission: emotes.command.flail
  grumble:
    description: Grumble!
    usage: /grumble
    default: op
    permission: emotes.command.grumble
  argue:
    description: Argue with a player!
    usage: /argue <player>
    default: op
    permission: emotes.command.argue
  love:
    description: Show your love to a player!
    usage: /love <player>
    default: op
    permission: emotes.command.love
  hate:
    description: Express your hate towards a player!
    usage: /hate <player>
    default: op
    permission: emotes.command.hate
  poke:
    description: Poke a player!
    usage: /poke <player>
    default: op
    permission: emotes.command.poke
  smack:
    description: Smack a player!
    usage: /smack <player>
    default: op
    permission: emotes.command.smack
  facepalm:
    description: Facepalm!
    usage: /facepalm
    default: op
    permission: emotes.command.facepalm
  whistle:
    description: Whistle!
    usage: /whistle <player>
    default: op
    permission: emotes.command.whistle

permissions:
  emotes.*:
    description: Gives access to all Emotes commands
    children: 
      emotes.command.*: true
      emotes.command.argue: true
      emotes.command.emotes.*: true
      emotes.command.emotes.cooldown: true
      emotes.command.emotes.cooldown.*: true
      emotes.command.emotes.cooldown.change: true
      emotes.command.emotes.cooldown.default: true
      emotes.command.emotes.cooldown.show: true
      emotes.command.emotes.use: true
      emotes.command.facepalm: true
      emotes.command.flail: true
      emotes.command.glomp: true
      emotes.command.grumble: true
      emotes.command.hate: true
      emotes.command.hug: true
      emotes.command.kick: true
      emotes.command.kiss: true
      emotes.command.love: true
      emotes.command.poke: true
      emotes.command.smack: true
      emotes.command.teabag: true
      emotes.command.wave: true
      emotes.command.whistle: true
      emotes.command.wink: true
  emotes.command.*:
    description: Gives access to all commands that needs the emotes.command permission
    children:
      emotes.command.argue: true
      emotes.command.emotes.*: true
      emotes.command.emotes.cooldown: true
      emotes.command.emotes.cooldown.*: true
      emotes.command.emotes.cooldown.change: true
      emotes.command.emotes.cooldown.default: true
      emotes.command.emotes.cooldown.show: true
      emotes.command.emotes.use: true
      emotes.command.facepalm: true
      emotes.command.flail: true
      emotes.command.glomp: true
      emotes.command.grumble: true
      emotes.command.hate: true
      emotes.command.hug: true
      emotes.command.kick: true
      emotes.command.kiss: true
      emotes.command.love: true
      emotes.command.poke: true
      emotes.command.smack: true
      emotes.command.teabag: true
      emotes.command.wave: true
      emotes.command.whistle: true
      emotes.command.wink: true
  emotes.command.argue:
    description: Gives access to /argue
    default: op
  emotes.command.emotes.*:
    description: Gives access to all /emotes commands
    children:
      emotes.command.emotes.cooldown: true
      emotes.command.emotes.cooldown.*: true
      emotes.command.emotes.cooldown.change: true
      emotes.command.emotes.cooldown.default: true
      emotes.command.emotes.cooldown.show: true
      emotes.command.emotes.use: true
    default: op
  emotes.command.emotes.cooldown:
    description: Gives access to /emotes cooldown
    default: op
  emotes.command.emotes.cooldown.*:
    description: Gives access to all /emotes cooldown commands
    children:
      emotes.command.emotes.cooldown.change: true
      emotes.command.emotes.cooldown.default: true
      emotes.command.emotes.cooldown.show: true
    default: op
  emotes.command.emotes.cooldown.change:
    description: Gives access to /emotes cooldown change
    default: op
  emotes.command.emotes.cooldown.default:
    description: Gives access to /emotes cooldown default
    default: op
  emotes.command.emotes.cooldown.show:
    description: Gives access to /emotes cooldown show
    default: op
  emotes.command.emotes.use:
    description: Gives access to /emotes
    default: op
  emotes.command.facepalm:
    description: Gives access to /facepalm
    default: op
  emotes.command.flail:
    description: Gives access to /flail
    default: op
  emotes.command.glomp:
    description: Gives access to /glomp
    default: op
  emotes.command.grumble:
    description: Gives access to /grumble
    default: op
  emotes.command.hate:
    description: Gives access to /hate
    default: op
  emotes.command.hug:
    description: Gives access to /hug
    default: op
  emotes.command.kick:
    description: Gives access to /ekick, /emote_kick, /emoteskick or /emotekick
    default: op
  emotes.command.kiss:
    description: Gives access to /kiss
    default: op
  emotes.command.love:
    description: Gives access to /love
    default: op
  emotes.command.poke:
    description: Gives access to /poke
    default: op
  emotes.command.smack:
    description: Gives access to /smack
    default: op
  emotes.command.teabag:
    description: Gives access to /teabag
    default: op
  emotes.command.wave:
    description: Gives access to /wave
    default: op
  emotes.command.whistle:
    description: Gives access to /whistle
    default: op
  emotes.command.wink:
    description: Gives access to /wink
    default: op